title: François Pilet
author: François Pilet
email: contact@francoispilet.net
description: >-
  Journaliste d'investigation spécialisé dans la finance, la banque, 
  et la fiscalité internationale. Fondateur de Gotham City.
url: 'https://francoispilet.net'
baseurl: ''
twitter_username: fpilet
github_username: francoispilet

# Configuration du thème
theme: minima
minima:
  date_format: "%d %b %Y"
  social_links:
    twitter: fpilet
    github: francoispilet

# Structure du site
permalink: /:title/
show_excerpts: true
excerpt_separator: <!--more-->

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclusions
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
